#!/bin/bash
# Monitor Streamlit Cloud deployment status

echo "🔍 Deployment Status Monitor"
echo "=============================="
echo ""
echo "✅ Fix Applied: packages.txt cleaned (removed comments)"
echo "✅ Changes Pushed: Commit 704342f pushed to main branch"
echo ""
echo "⏳ Streamlit Cloud will auto-redeploy in 2-3 minutes"
echo ""
echo "📊 What to Check:"
echo ""
echo "1. Go to: https://share.streamlit.io/"
echo "2. Open your app: knowledge-ragbot"
echo "3. Check the logs tab"
echo ""
echo "✅ Expected Log Output (if successful):"
echo "   - 🐙 Cloning repository..."
echo "   - 📦 Processing dependencies..."
echo "   - ✅ Dependencies installed successfully"
echo "   - 🚀 Starting application..."
echo ""
echo "Your app URL: https://knowledge-ragbot-6kwqvc6giy2crhkortxswc.streamlit.app/"
echo ""
echo "⏰ Current time: $(date)"
echo "⏰ Check again in: 3 minutes"
echo ""
echo "🎉 Once deployed, test:"
echo "   1. Upload a PDF"
echo "   2. Ask a question"
echo "   3. Check sources appear"
echo ""
echo "Need help? Check PACKAGES_TXT_FIX.md for details"
